# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi

class Ui_Principal(object):                                 #Interfaz importada de QT Designer
    def setupUi(self, Principal):
        Principal.setObjectName("Principal")
        Principal.resize(798, 612)
        Principal.setMinimumSize(QtCore.QSize(400, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 241, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 202, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 81, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 109, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 209, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 241, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 202, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 81, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 109, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 209, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 81, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 241, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 202, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 81, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 109, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 81, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 81, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 163, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Principal.setPalette(palette)
        Principal.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(Principal)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 800, 600))
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setMaximumSize(QtCore.QSize(800, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameup = QtWidgets.QFrame(self.frame)
        self.frameup.setEnabled(True)
        self.frameup.setStyleSheet("background-color: rgb(42, 85, 101);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(116, 163, 173);\n"
"alternate-background-color: rgb(116, 163, 173);")
        self.frameup.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameup.setLineWidth(3)
        self.frameup.setObjectName("frameup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_inicio = QtWidgets.QPushButton(self.frameup)
        self.btn_inicio.setObjectName("btn_inicio")
        self.horizontalLayout.addWidget(self.btn_inicio)
        self.btn_tarifas = QtWidgets.QPushButton(self.frameup)
        self.btn_tarifas.setObjectName("btn_tarifas")
        self.horizontalLayout.addWidget(self.btn_tarifas)
        self.btn_modificar = QtWidgets.QPushButton(self.frameup)
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout.addWidget(self.btn_modificar)
        self.btn_admin = QtWidgets.QPushButton(self.frameup)
        self.btn_admin.setObjectName("btn_admin")
        self.horizontalLayout.addWidget(self.btn_admin)
        self.btn_salir = QtWidgets.QPushButton(self.frameup)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout.addWidget(self.btn_salir)
        self.frame_3 = QtWidgets.QFrame(self.frameup)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frameup)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frameup)
        self.framecont = QtWidgets.QFrame(self.frame)
        self.framecont.setMinimumSize(QtCore.QSize(800, 500))
        self.framecont.setMaximumSize(QtCore.QSize(800, 600))
        self.framecont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framecont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framecont.setObjectName("framecont")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.framecont)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.framecont)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_inicio = QtWidgets.QWidget()
        self.pg_inicio.setObjectName("pg_inicio")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.pg_inicio)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameciz = QtWidgets.QFrame(self.pg_inicio)
        self.frameciz.setMinimumSize(QtCore.QSize(330, 400))
        self.frameciz.setMaximumSize(QtCore.QSize(350, 514))
        self.frameciz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameciz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameciz.setObjectName("frameciz")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameciz)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_calendar = QtWidgets.QLabel(self.frameciz)
        self.label_calendar.setMinimumSize(QtCore.QSize(0, 37))
        self.label_calendar.setMaximumSize(QtCore.QSize(400, 37))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_calendar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_calendar.setFont(font)
        self.label_calendar.setStyleSheet("background-color: rgb(42, 85, 101);\n"
"color: rgb(255, 255, 255);")
        self.label_calendar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_calendar.setObjectName("label_calendar")
        self.verticalLayout_4.addWidget(self.label_calendar)
        self.calendarW = QtWidgets.QCalendarWidget(self.frameciz)
        self.calendarW.setEnabled(True)
        self.calendarW.setMinimumSize(QtCore.QSize(348, 220))
        self.calendarW.setMaximumSize(QtCore.QSize(348, 220))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        self.calendarW.setPalette(palette)
        self.calendarW.setMouseTracking(True)
        self.calendarW.setTabletTracking(False)
        self.calendarW.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.calendarW.setAutoFillBackground(True)
        self.calendarW.setStyleSheet("")
        self.calendarW.setMinimumDate(QtCore.QDate(2022, 9, 24))
        self.calendarW.setMaximumDate(QtCore.QDate(2023, 2, 24))
        self.calendarW.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarW.setGridVisible(True)
        self.calendarW.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarW.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.SingleLetterDayNames)
        self.calendarW.setNavigationBarVisible(True)
        self.calendarW.setDateEditEnabled(True)
        self.calendarW.setObjectName("calendarW")
        self.verticalLayout_4.addWidget(self.calendarW)
        self.frame_5 = QtWidgets.QFrame(self.frameciz)
        self.frame_5.setMinimumSize(QtCore.QSize(300, 200))
        self.frame_5.setMaximumSize(QtCore.QSize(400, 200))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelFinicio = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelFinicio.setFont(font)
        self.labelFinicio.setObjectName("labelFinicio")
        self.horizontalLayout_10.addWidget(self.labelFinicio)
        self.lineEdit_initialdate = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_initialdate.setReadOnly(True)
        self.lineEdit_initialdate.setObjectName("lineEdit_initialdate")
        self.horizontalLayout_10.addWidget(self.lineEdit_initialdate)
        self.horizontalLayout_10.setStretch(0, 3)
        self.horizontalLayout_10.setStretch(1, 5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labeldays = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labeldays.setFont(font)
        self.labeldays.setObjectName("labeldays")
        self.horizontalLayout_9.addWidget(self.labeldays)
        self.lineEdit_days = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_days.setReadOnly(False)
        self.lineEdit_days.setObjectName("lineEdit_days")
        self.horizontalLayout_9.addWidget(self.lineEdit_days)
        self.horizontalLayout_9.setStretch(0, 3)
        self.horizontalLayout_9.setStretch(1, 5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblfinaldate = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblfinaldate.setFont(font)
        self.lblfinaldate.setObjectName("lblfinaldate")
        self.horizontalLayout_8.addWidget(self.lblfinaldate)
        self.lineEdit_finaldate = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_finaldate.setReadOnly(True)
        self.lineEdit_finaldate.setObjectName("lineEdit_finaldate")
        self.horizontalLayout_8.addWidget(self.lineEdit_finaldate)
        self.horizontalLayout_8.setStretch(0, 3)
        self.horizontalLayout_8.setStretch(1, 5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelsalon = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelsalon.setFont(font)
        self.labelsalon.setObjectName("labelsalon")
        self.horizontalLayout_7.addWidget(self.labelsalon)
        self.comboBoxSalon = QtWidgets.QComboBox(self.frame_5)
        self.comboBoxSalon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxSalon.setObjectName("comboBoxSalon")
        self.comboBoxSalon.addItem("")
        self.comboBoxSalon.addItem("")
        self.comboBoxSalon.addItem("")
        self.comboBoxSalon.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBoxSalon)
        self.horizontalLayout_7.setStretch(0, 3)
        self.horizontalLayout_7.setStretch(1, 5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.btn_dispon = QtWidgets.QPushButton(self.frame_5)
        self.btn_dispon.setObjectName("btn_dispon")
        self.horizontalLayout_11.addWidget(self.btn_dispon)
        self.btnreservar = QtWidgets.QPushButton(self.frame_5)
        self.btnreservar.setObjectName("btnreservar")
        self.horizontalLayout_11.addWidget(self.btnreservar)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        self.horizontalLayout_11.setStretch(2, 2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_18.addWidget(self.lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.verticalLayout_8.setStretch(2, 1)
        self.verticalLayout_8.setStretch(3, 1)
        self.verticalLayout_8.setStretch(4, 1)
        self.verticalLayout_4.addWidget(self.frame_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frameciz)
        self.framecder = QtWidgets.QFrame(self.pg_inicio)
        self.framecder.setEnabled(False)
        self.framecder.setMinimumSize(QtCore.QSize(400, 0))
        self.framecder.setMaximumSize(QtCore.QSize(400, 16777215))
        self.framecder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framecder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framecder.setObjectName("framecder")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.framecder)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.framecder)
        self.label_8.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(42, 85, 101);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setHorizontalSpacing(15)
        self.formLayout_2.setVerticalSpacing(12)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_ID = QtWidgets.QLabel(self.framecder)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ID.setFont(font)
        self.lbl_ID.setObjectName("lbl_ID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_ID)
        self.lineEdit_ID = QtWidgets.QLineEdit(self.framecder)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ID)
        self.Nombre = QtWidgets.QLabel(self.framecder)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Nombre.setFont(font)
        self.Nombre.setObjectName("Nombre")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Nombre)
        self.lineEdit_Nombre = QtWidgets.QLineEdit(self.framecder)
        self.lineEdit_Nombre.setObjectName("lineEdit_Nombre")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Nombre)
        self.lbl_apellido = QtWidgets.QLabel(self.framecder)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_apellido.setFont(font)
        self.lbl_apellido.setObjectName("lbl_apellido")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_apellido)
        self.lineEdit_Apellidos = QtWidgets.QLineEdit(self.framecder)
        self.lineEdit_Apellidos.setObjectName("lineEdit_Apellidos")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Apellidos)
        self.lbl_celular = QtWidgets.QLabel(self.framecder)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_celular.setFont(font)
        self.lbl_celular.setObjectName("lbl_celular")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_celular)
        self.lineEdit_Cel = QtWidgets.QLineEdit(self.framecder)
        self.lineEdit_Cel.setObjectName("lineEdit_Cel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Cel)
        self.lbl_correo = QtWidgets.QLabel(self.framecder)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_correo.setFont(font)
        self.lbl_correo.setObjectName("lbl_correo")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_correo)
        self.lineEdit_Correo = QtWidgets.QLineEdit(self.framecder)
        self.lineEdit_Correo.setObjectName("lineEdit_Correo")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Correo)
        self.label_9 = QtWidgets.QLabel(self.framecder)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.textEdit_com = QtWidgets.QTextEdit(self.framecder)
        self.textEdit_com.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textEdit_com.setObjectName("textEdit_com")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textEdit_com)
        self.btn_enviar = QtWidgets.QPushButton(self.framecder)
        self.btn_enviar.setObjectName("btn_enviar")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btn_enviar)
        self.btn_cancelar = QtWidgets.QPushButton(self.framecder)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_cancelar)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.framecder)
        self.stackedWidget.addWidget(self.pg_inicio)
        self.pg_tarifas = QtWidgets.QWidget()
        self.pg_tarifas.setObjectName("pg_tarifas")
        self.frame_7 = QtWidgets.QFrame(self.pg_tarifas)
        self.frame_7.setGeometry(QtCore.QRect(10, 10, 700, 350))
        self.frame_7.setMinimumSize(QtCore.QSize(700, 350))
        self.frame_7.setMaximumSize(QtCore.QSize(700, 400))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setStyleSheet("background-color: rgb(42, 85, 101);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 2)
        self.verticalLayout_3.setStretch(3, 2)
        self.verticalLayout_3.setStretch(4, 2)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.pg_tarifas)
        self.pg_admin = QtWidgets.QWidget()
        self.pg_admin.setObjectName("pg_admin")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pg_admin)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.pg_admin)
        self.frame_8.setMinimumSize(QtCore.QSize(600, 450))
        self.frame_8.setMaximumSize(QtCore.QSize(600, 500))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setMinimumSize(QtCore.QSize(0, 37))
        self.label_7.setStyleSheet("background-color: rgb(42, 85, 101);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.btn_refresh = QtWidgets.QPushButton(self.frame_8)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_5.addWidget(self.btn_refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.pg_admin)
        self.pg_modificar = QtWidgets.QWidget()
        self.pg_modificar.setObjectName("pg_modificar")
        self.frame_9 = QtWidgets.QFrame(self.pg_modificar)
        self.frame_9.setGeometry(QtCore.QRect(0, 10, 687, 444))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(300, 50))
        self.frame_10.setMaximumSize(QtCore.QSize(400, 150))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelFinicio_2 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelFinicio_2.setFont(font)
        self.labelFinicio_2.setObjectName("labelFinicio_2")
        self.horizontalLayout_12.addWidget(self.labelFinicio_2)
        self.lineEdit_initialdate_2 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_initialdate_2.setReadOnly(True)
        self.lineEdit_initialdate_2.setObjectName("lineEdit_initialdate_2")
        self.horizontalLayout_12.addWidget(self.lineEdit_initialdate_2)
        self.horizontalLayout_12.setStretch(0, 3)
        self.horizontalLayout_12.setStretch(1, 5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labeldays_2 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labeldays_2.setFont(font)
        self.labeldays_2.setObjectName("labeldays_2")
        self.horizontalLayout_13.addWidget(self.labeldays_2)
        self.lineEdit_days_2 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_days_2.setReadOnly(False)
        self.lineEdit_days_2.setObjectName("lineEdit_days_2")
        self.horizontalLayout_13.addWidget(self.lineEdit_days_2)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_13.setStretch(1, 5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblfinaldate_2 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblfinaldate_2.setFont(font)
        self.lblfinaldate_2.setObjectName("lblfinaldate_2")
        self.horizontalLayout_14.addWidget(self.lblfinaldate_2)
        self.lineEdit_finaldate_2 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_finaldate_2.setReadOnly(True)
        self.lineEdit_finaldate_2.setObjectName("lineEdit_finaldate_2")
        self.horizontalLayout_14.addWidget(self.lineEdit_finaldate_2)
        self.horizontalLayout_14.setStretch(0, 3)
        self.horizontalLayout_14.setStretch(1, 5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelsalon_2 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelsalon_2.setFont(font)
        self.labelsalon_2.setObjectName("labelsalon_2")
        self.horizontalLayout_15.addWidget(self.labelsalon_2)
        self.comboBoxSalon_2 = QtWidgets.QComboBox(self.frame_10)
        self.comboBoxSalon_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxSalon_2.setObjectName("comboBoxSalon_2")
        self.comboBoxSalon_2.addItem("")
        self.comboBoxSalon_2.addItem("")
        self.comboBoxSalon_2.addItem("")
        self.comboBoxSalon_2.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBoxSalon_2)
        self.horizontalLayout_15.setStretch(0, 3)
        self.horizontalLayout_15.setStretch(1, 5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(2, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_6.addWidget(self.frame_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 4, -1, -1)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.lbl_ID_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ID_2.setFont(font)
        self.lbl_ID_2.setObjectName("lbl_ID_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_ID_2)
        self.lineEdit_ID_2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_ID_2.setObjectName("lineEdit_ID_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ID_2)
        self.Nombre_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Nombre_2.setFont(font)
        self.Nombre_2.setObjectName("Nombre_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Nombre_2)
        self.lineEdit_Nombre_2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_Nombre_2.setObjectName("lineEdit_Nombre_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Nombre_2)
        self.lbl_apellido_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_apellido_2.setFont(font)
        self.lbl_apellido_2.setObjectName("lbl_apellido_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_apellido_2)
        self.lineEdit_Apellidos_2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_Apellidos_2.setObjectName("lineEdit_Apellidos_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Apellidos_2)
        self.lbl_celular_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_celular_2.setFont(font)
        self.lbl_celular_2.setObjectName("lbl_celular_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_celular_2)
        self.lineEdit_Cel_2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_Cel_2.setObjectName("lineEdit_Cel_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Cel_2)
        self.lbl_correo_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_correo_2.setFont(font)
        self.lbl_correo_2.setObjectName("lbl_correo_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_correo_2)
        self.lineEdit_Correo_2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_Correo_2.setObjectName("lineEdit_Correo_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Correo_2)
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textEdit_com_2 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_com_2.setMinimumSize(QtCore.QSize(0, 100))
        self.textEdit_com_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit_com_2.setObjectName("textEdit_com_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textEdit_com_2)
        self.btn_modificar_2 = QtWidgets.QPushButton(self.frame_9)
        self.btn_modificar_2.setObjectName("btn_modificar_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btn_modificar_2)
        self.btn_cancelar_2 = QtWidgets.QPushButton(self.frame_9)
        self.btn_cancelar_2.setObjectName("btn_cancelar_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.btn_cancelar_2)
        self.btn_cancelar_3 = QtWidgets.QPushButton(self.frame_9)
        self.btn_cancelar_3.setObjectName("btn_cancelar_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_cancelar_3)
        self.horizontalLayout_6.addLayout(self.formLayout)
        self.stackedWidget.addWidget(self.pg_modificar)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.framecont)
        Principal.setCentralWidget(self.centralwidget)
        self.retranslateUi(Principal)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        _translate = QtCore.QCoreApplication.translate
        Principal.setWindowTitle(_translate("Principal", "Gestión de reservas - Salón de eventos"))
        self.btn_inicio.setText(_translate("Principal", "Inicio"))
        self.btn_tarifas.setText(_translate("Principal", "Tarifas"))
        self.btn_modificar.setText(_translate("Principal", "Modificar"))
        self.btn_admin.setText(_translate("Principal", "Lista de eventos"))
        self.btn_salir.setText(_translate("Principal", "Salir"))
        self.label_calendar.setText(_translate("Principal", "Fechas:"))
        self.labelFinicio.setText(_translate("Principal", "Fecha inicial:"))
        self.labeldays.setText(_translate("Principal", "Cantidad de días:"))
        self.lblfinaldate.setText(_translate("Principal", "Fecha final:"))
        self.labelsalon.setText(_translate("Principal", "Salón:"))
        self.comboBoxSalon.setItemText(0, _translate("Principal", "Salón 1 (Max. 400 personas)"))
        self.comboBoxSalon.setItemText(1, _translate("Principal", "Salón 2 (Máx. 200 personas)"))
        self.comboBoxSalon.setItemText(2, _translate("Principal", "Salón 3 (Máx. 100 personas)"))
        self.comboBoxSalon.setItemText(3, _translate("Principal", "Salón 4 (Máx. 50 personas)"))
        self.btn_dispon.setText(_translate("Principal", "Consultar disponibilidad"))
        self.btnreservar.setText(_translate("Principal", "Reservar"))
        self.label_8.setText(_translate("Principal", "Reserva"))
        self.lbl_ID.setText(_translate("Principal", "ID:"))
        self.Nombre.setText(_translate("Principal", "<html><head/><body><p>Nombre:</p></body></html>"))
        self.lbl_apellido.setText(_translate("Principal", "Apellidos:"))
        self.lbl_celular.setText(_translate("Principal", "Celular:"))
        self.lbl_correo.setText(_translate("Principal", "Correo:"))
        self.label_9.setText(_translate("Principal", "Comentarios:"))
        self.btn_enviar.setText(_translate("Principal", "Enviar"))
        self.btn_cancelar.setText(_translate("Principal", "Cancelar"))
        self.label_4.setText(_translate("Principal", "Costo por día"))
        self.label_5.setText(_translate("Principal", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Salón 1. Capacidad máxima de 400 personas</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Costo: COP $ 4.000.000 por día</span></p></body></html>"))
        self.label_3.setText(_translate("Principal", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Salón 2. Capacidad máxima de 200 personas</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Costo: COP $ 2.000.000 por día</span></p></body></html>"))
        self.label.setText(_translate("Principal", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Salón 3. Capacidad máxima de 100 personas</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Costo: COP $ 1.000.000 por día</span></p></body></html>"))
        self.label_6.setText(_translate("Principal", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Salón 4. Capacidad máxima de 50 personas</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Costo: COP $ 500.000 por día</span></p></body></html>"))
        self.label_7.setText(_translate("Principal", "Listado de eventos agendados"))
        self.btn_refresh.setText(_translate("Principal", "Actualizar"))
        self.labelFinicio_2.setText(_translate("Principal", "Fecha Reserva:"))
        self.labeldays_2.setText(_translate("Principal", "Cantidad de días:"))
        self.lblfinaldate_2.setText(_translate("Principal", "Fecha final:"))
        self.labelsalon_2.setText(_translate("Principal", "Salón:"))
        self.comboBoxSalon_2.setItemText(0, _translate("Principal", "Salón 1 (Max. 400 personas)"))
        self.comboBoxSalon_2.setItemText(1, _translate("Principal", "Salón 2 (Máx. 200 personas)"))
        self.comboBoxSalon_2.setItemText(2, _translate("Principal", "Salón 3 (Máx. 100 personas)"))
        self.comboBoxSalon_2.setItemText(3, _translate("Principal", "Salón 4 (Máx. 50 personas)"))
        self.lbl_ID_2.setText(_translate("Principal", "ID:"))
        self.Nombre_2.setText(_translate("Principal", "<html><head/><body><p>Nombre:</p></body></html>"))
        self.lbl_apellido_2.setText(_translate("Principal", "Apellidos:"))
        self.lbl_celular_2.setText(_translate("Principal", "Celular:"))
        self.lbl_correo_2.setText(_translate("Principal", "Correo:"))
        self.label_2.setText(_translate("Principal", "Comentarios:"))
        self.btn_modificar_2.setText(_translate("Principal", "Modificar"))
        self.btn_cancelar_2.setText(_translate("Principal", "Cancelar"))
        self.btn_cancelar_3.setText(_translate("Principal", "Cancelar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_Principal()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())

